[[redirects]]
  from = "/proof/*"
  to = "https://lace-proof-pub.preprod.midnight.network/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
